import React from 'react'
import { useRouter } from 'next/router'
import Courses from '../../components/courses/courses'
import Wrapper from '../../components/ui/wrapper'
import Head from 'next/head'
import { filterCourses } from '../../constants/constants'
import { ArrowSmLeftIcon } from '@heroicons/react/outline'

const Slug = () => {

    const router = useRouter()

    const courses = filterCourses(router.query)

    if(!router.query) {
        return 'Loading...'
    }

    return (
        <Wrapper>
            <Head>
                <title>Filter Courses Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <p className="flex items-center mb-4 text-lg text-blue-500 cursor-pointer font-medium" onClick={() => router.push('/all-courses')}>
                <ArrowSmLeftIcon className="h-7 mr-2"/>
                GET BACK
            </p>
            <h1 className="font-bold text-3xl">
                {router.query?.category?.charAt(0).toUpperCase() + router.query?.category?.slice(1) || 'All Courses'}
            </h1>
            <Courses courses={courses}/>
        </Wrapper>
    )
}

export default Slug
