import Head from 'next/head'
import Typed from 'react-typed'
import { ArrowSmRightIcon } from '@heroicons/react/outline'
import { useRouter } from 'next/router'
import Image from 'next/image'
import Wrapper from '../components/ui/wrapper'

export default function Home() {

	const router = useRouter()

	return (
    	<div>
      		<Head>
        		<title>Home Page</title>
        		<meta name="description" content="Generated by create next app" />
        		<link rel="icon" href="/favicon.ico" />
      		</Head>
      
				<Wrapper>
					<div className="flex text-lg items-center lg:items-start flex-col-reverse lg:flex-row justify-between">
						<div>
							<div className="mb-7">
								<h1 className="font-bold text-6xl border-b-4 w-max pb-3 mb-5 border-green-500">HIRE ME.</h1>
								<p>Hello, my name is Hendra Adri. I'm working as <br />
									<span className="text-blue-500 text-xl font-medium">
										<Typed 
											strings={['Fullstack Developer',
													'Mobile Apps Developer',
													'UI/UX Designer',
													'Design Graphic',
													'Product Designer']}
											typeSpeed={60}
											backSpeed={30}
											loop/>
									</span>
								</p>
							</div>

							{/* About Me */}
							<div className="mb-7">
								<h3 className="mb-2 border-b-2 border-green-500 w-max">About Me</h3>
								<p>
									I have experienced for this job more than 5 years. I'm freelancer and <br /> teach also about programming language from Indonesian.<br/>
									Enjoy taking complex problem for building best apps and design is my passion. 
								</p>
							</div>

							{/* My Project */}
							<div className="mb-7">
								<h3 className="mb-2 border-b-2 border-green-500 w-max">My Projects</h3>
								<div className="flex items-center">
									<ArrowSmRightIcon className="h-6 mr-3"/>
									<p className="text-blue-500 cursor-pointer" onClick={() => router.push('/all-projects')}>My Projects</p>
								</div>
							</div>

							{/* My Course */}
							<div className="mb-7">
								<h3 className="mb-2 border-b-2 border-green-500 w-max">My Courses</h3>
								<div className="flex items-center">
									<ArrowSmRightIcon className="h-6 mr-3"/>
									<p className="text-blue-500 cursor-pointer" onClick={() => router.push('/all-courses')} onClick={() => router.push('/all-courses')}>All Courses</p>
								</div>
								<div className="flex items-center">
									<ArrowSmRightIcon className="h-6 mr-3"/>
									<p 
										className="text-blue-500 cursor-pointer" 
										onClick={() => router.push('/all-courses/courses/filter?category=UI UX')}>UI/UX Design</p>
								</div>
								<div className="flex items-center">
									<ArrowSmRightIcon className="h-6 mr-3"/>
									<p 
										className="text-blue-500 cursor-pointer" 
										onClick={() => router.push('/all-courses/courses/filter?category=Desain Grafis')}>Design Graphic</p>
								</div>
							</div>
							
							{/* Contact Me */}
							<div>
								<h3 className="mb-2 border-b-2 border-green-500 w-max">Contact Me</h3>
								<p>Address : <span className="text-blue-500 cursor-pointer">Purbalingga, Indonesia</span></p>
								<p>Email : <span className="text-blue-500 cursor-pointer">permanahendra@gmail.com</span></p>
								<p>No Telp : <span className="text-blue-500 cursor-pointer">0895377111674</span></p>
								<p>Github : <span className="text-blue-500 cursor-pointer">github.com/henndev</span></p>
								<p>Linkedin : <span className="text-blue-500 cursor-pointer">github.com/henndev</span></p>
							</div>
						</div>


						<Image 
							layout="intrinsic"
							src="/images/img-porto.png"
							height={450}
							width={450}
						/>
					</div>	
				</Wrapper>						
    	</div>
  	)
}
